/**
 * Tool: generate_project
 *
 * Generates a project ZIP with selected skills.
 * Returns a download URL or base64 data.
 */

export const generateProjectDefinition = {
  type: 'function' as const,
  function: {
    name: 'generate_project',
    description: 'Generate a downloadable project ZIP containing selected skills and a tailored CLAUDE.md.',
    parameters: {
      type: 'object',
      properties: {
        skillSlugs: {
          type: 'array',
          items: { type: 'string' },
          description: 'List of skill slugs to include in the project',
        },
        description: {
          type: 'string',
          description: 'Brief description of what the user is building (used to tailor CLAUDE.md)',
        },
      },
      required: ['skillSlugs', 'description'],
    },
  },
};

export async function executeGenerateProject(args: {
  skillSlugs: string[];
  description: string;
}): Promise<string> {
  if (args.skillSlugs.length === 0) {
    return JSON.stringify({ error: 'No skills selected. Please specify at least one skill slug.' });
  }

  // Bundle all requested skills into a ZIP
  const JSZip = (await import('jszip')).default;
  const { getAllSkills, getCompanionsFor } = await import('@/platform/lib/skills');
  const allSkills = getAllSkills();

  const zip = new JSZip();
  const included = new Set<string>();

  for (const slug of args.skillSlugs) {
    const skill = allSkills.find(s => s.slug === slug);
    if (!skill || included.has(slug)) continue;
    zip.file(`skills/${skill.slug}.md`, skill.content);
    included.add(slug);

    // Include companion skills
    const companions = getCompanionsFor(slug);
    for (const comp of companions) {
      if (!included.has(comp.slug)) {
        zip.file(`skills/${comp.slug}.md`, comp.content);
        included.add(comp.slug);
      }
    }
  }

  if (included.size === 0) {
    return JSON.stringify({ error: 'None of the specified skill slugs were found.' });
  }

  // Add a CLAUDE.md tailored to the project
  const claudeMd = `# ${args.description}\n\nGenerated by AI Centre.\n\n## Skills included\n${[...included].map(s => `- ${s}`).join('\n')}\n`;
  zip.file('CLAUDE.md', claudeMd);

  const buffer = await zip.generateAsync({ type: 'nodebuffer' });
  const base64 = buffer.toString('base64');
  const projectName = args.description.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40) || 'project';
  const fileName = `${projectName}.zip`;

  return JSON.stringify({
    success: true,
    skillCount: included.size,
    fileName,
    base64,
    message: `Project ZIP generated with ${included.size} skill(s). The download button is now available.`,
  });
}
